### ISSUE TITLE
single max_val no potential well found

### ISSUE THREAD

**Issue by scpalbright** [blond-org/blond_common#15] opened 2019-08-06 07:19 UTC
rf_functions.potential.find_potential_wells_cubic does not find a potential well when only 1 maxima is returned by minmax_location_cubic.  Not clear if the error lies in find_potential_wells_cubic or minmax_location_cubic.

Vertical red line shows detected max location, with a max_val = 574.9......; the 0th element has value 577.3.......

![image](https://user-images.githubusercontent.com/11768875/62519011-0c3dec00-b82b-11e9-94fd-1a9c9cc5b2ec.png)

**Comment by alasheen** [comment] 2019-08-06 08:00
Investigating!

**Comment by alasheen** [comment] 2019-08-06 13:22
**Bug fixed in data_types branch commit f96f657**

**The find_potential_wells_cubic is now treating correctly the cases where only 1 maximum is found but where the 0th element (or the last), is higher than that maximum, as shown in next fig. This was a bug that is now corrected.**

![no_margin](https://user-images.githubusercontent.com/6851107/62542323-dcf3a300-b85b-11e9-925e-65ea1f6fe707.png)

However, note that if the 0th element is smaller than the detected maximum (e.g. because slight phase offset), then the potential well cannot be well defined and it is expected that the find_potential_wells_cubic function does not return anything, see next fig.

![no_margin_bad_case](https://user-images.githubusercontent.com/6851107/62542416-044a7000-b85c-11e9-9571-771f034ed9a9.png)

By default, the rf potential is computed by default on the range [0, t_rev]. This is why the 0th element in the issue is not detected as a maximum (there is no point to the left for the derivative to numerically cross 0). A better practice consists of having margin on the rf potential range, by manually passing the time_bounds option to rf_potential_generation, see next fig.

![margin](https://user-images.githubusercontent.com/6851107/62542403-fdbbf880-b85b-11e9-905d-f0b0eb21c05b.png)

We could improve the options of rf_potential_generation to have a "margin" option, that would automatically take +- x % of margin to the time array. I will open an issue to collect the expected input/output and features of functions in rf_function package.

With no further comment I'll close the issue.

**Comment by scpalbright** [comment] 2019-08-06 13:46
I propose having it raise an exception in the event that no potential well can be found, it would be clearer for debugging than returning an empty list.

**Comment by alasheen** [comment] 2019-08-06 15:32
I agree, I'll put that in the list of things of things to add to the function :)

**Closed by alasheen** 2019-08-06 15:32 UTC
Labels: bug
